name: Upload Python Package

on:
  release:
    types: [published, edited]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
    - uses: actions/checkout@v7

    - name: Install uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990

    - name: Build package
      run: uv build
      
    - name: Publish package to PyPI
      run: uv publish --check-url https://pypi.org/simple/

    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: python-package-artifacts
        path: dist/
